# Generated by Django 5.2 on 2025-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='color',
        ),
        migrations.RemoveField(
            model_name='house',
            name='description',
        ),
        migrations.RemoveField(
            model_name='house',
            name='emblem_url',
        ),
        migrations.AddField(
            model_name='house',
            name='animal',
            field=models.CharField(default='Unknown', help_text='The animal symbol of the house (e.g., Lion).', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='colors',
            field=models.CharField(default='Unknown', help_text='The house colors (e.g., Scarlet and Gold).', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='founder',
            field=models.CharField(default='Unknown', help_text='The founder of the house (e.g., Godric Gryffindor).', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='traits',
            field=models.TextField(default='Unknown', help_text='Key traits associated with this house (e.g., Bravery, Loyalty).'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(help_text='The name of the house (e.g., Gryffindor, Slytherin).', max_length=50, unique=True),
        ),
    ]
